########################################################################################################################
## Copyright (c) 2018 A Bit of Help, Inc. - All Rights Reserved, Worldwide.
## Use of this source code is governed by a MIT license that can be found in the LICENSE file.
########################################################################################################################